name: Go UI Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow from GitHub Actions UI

jobs:
  run-go-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19' # Specify the Go version you are using

    - name: Install ChromeDP
      run: |
        go mod tidy
        go get -u github.com/chromedp/chromedp

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run UI Tests in Headless Mode
      env:
        CHROMEDP_HEADLESS: 1  # Ensure headless mode is enabled
      run: |
        go test -v

    - name: Archive Test Results (if needed)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: go-ui-test-results
        path: test-report/
